### ISSUE TITLE
use table name different from module name

### ISSUE THREAD

**Issue by jordan0day** [inaka/sumo_db_mysql#6]
I've been digging through the project code, but it's not very apparent to me how (or if) I can use a name for my entity module  which is different from the table name in mysql.

This creates some problems if I have a table named `user`, since there's already a built-in `user` module in ERTS, so I wind up with an error like
`6:54:51.489 [error] gen_server 'wpool_pool-kiosk_sync_mysql-1' terminated with reason: call to undefined function user:sumo_schema/0 from sumo_utils:doc_transform/2 line 30`. (I assure you I've implemented `sumo_schema/0` for the `user` module 😄 )

So just curious if there's something I'm missing or if that's not an option?

**Comment by elbrujohalcon** [comment]
I think you've spotted a serious missing feature here!!
And it's not just for msyql store/backend, all the other backends/stores are affected as well.
The only different one is riak, and even there this thing is solved in a very poor way (i.e. adding the _bucket name_ as an option to the store, which ends up leading to having one store per doc and that's not how it should be).
I'll open an issue on sumo_db itself to add an extra field to docs configuration where we can put things like the schema name or the module name if they're not the same.
Thanks for spotting this, @jordan0day.

**Comment by elbrujohalcon** [comment]
I'm closing this issue to move the conversation to inaka/sumo_db#239
